WITH T1 AS
(
    SELECT *,RANK OVER(ORDER BY B.VOTES DESC) AS RK 
    FROM CANDIDATE C 
    JOIN
    (
        SELECT CANDIDATEID,COUNT(*) AS VOTES 
        FROM VOTE 
        GROUP BY CANDIDATEID
    )B 
    ON C.ID = B.CANDIDATEID
)

SELECT T1.NAME 
FROM T1 
WHERE T1.RK = 1
